

const GET_CATEGORIES = "GET_CATEGORIES"
const ADD_CATEGORY = "ADD_CATEGORY"
const GET_CATEGORY_TOPICS = "GET_CATEGORY_TOPICS"
const GET_TOPICS = "GET_TOPICS"
const ADD_TOPIC = "ADD_TOPIC"
const GET_TOPIC_LESSONS = "GET_TOPIC_LESSONS"
const ADD_LESSON = "ADD_LESSON"
const GET_LESSON_ATTEMPTS = "GET_LESSON_ATTEMPTS"
const ADD_ATTEMPT = "ADD_ATTEMPT"
const GET_PROFILE = "GET_PROFILE"
const GET_USER_LESSONS = "GET_USER_LESSONS"
const GET_CSRF_TOKEN = "GET_CSRF_TOKEN"
const LOG_IN_USER = "LOG_IN_USER"
const SIGN_UP_USER = "SIGN_UP_USER"
const ADD_COMMENT = "ADD_COMMENT"
const EDIT_COMMENT = "EDIT_COMMENT"
const ADD_REACTION = "ADD_REACTION"
const DELETE_REACTION = "DELETE_REACTION"
const LOGOUT = "LOGOUT"

export {
    GET_CATEGORIES,
    ADD_CATEGORY,
    GET_CATEGORY_TOPICS,
    GET_TOPICS,
    ADD_TOPIC,
    GET_TOPIC_LESSONS,
    ADD_LESSON,
    GET_LESSON_ATTEMPTS,
    ADD_ATTEMPT,
    GET_PROFILE,
    GET_USER_LESSONS,
    GET_CSRF_TOKEN,
    LOG_IN_USER,
    SIGN_UP_USER,
    ADD_COMMENT,
    EDIT_COMMENT,
    ADD_REACTION,
    DELETE_REACTION,
    LOGOUT,
}